apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-vs-dogs-backend
  labels:
    app: cats-vs-dogs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-vs-dogs-backend
  template:
    metadata:
      labels:
        app: cats-vs-dogs-backend
    spec:
      containers:
        - name: backend
          image: 2024ab05112/cats-vs-dogs-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-service:5000"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
