apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: cats-vs-dogs-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30800
  type: NodePort
